language: node_js

node_js:
  - 0.12
  - 4.2
  
before_script:
  - cp config/config.json.dist config/config.json
  - sed -i -e "s/%%API_KEY%%/${API_KEY}/g" config/config.json
  - sed -i -e "s/%%API_SECRET%%/${API_SECRET}/g" config/config.json
  - git clone https://bitbucket.org/solidshops/theme_unittests.git
  - sed -i -e  "s/%%THEME_FOLDER%%/theme_unittests/g" config/config.json
